### ISSUE TITLE
[Feature request] Named selector and removal operator

### ISSUE THREAD

**Issue by felixhao28** [adriank/ObjectPath#54]
For a family like this (the actually data can go very deep):

```yaml
name: Adam
gender: male
children:
  - name: Bran
    gender: male
  - name: Cindy
    gender: female
    children:
      - name: David
        gender: male
        children:
          - name: Helen
            gender: female
      - name: Eva
        gender: female
  - name: Frank
    gender: male
    children:
      - name: George
        gender: male
```

I'd like to find __Cindy and all female offsprings of Cindy__. There will be three steps to take:

1. Find Cindy: `$..*[@.name is 'Cindy'].name` => `Cindy`
2. Find all female offsprings of Cindy: `$..*[@.name is 'Cindy'].children..*[@.gender is female].name` => `Helen, Eva`
3. Add them together: `$..*[@.name is 'Cindy'].name + $..*[@.name is 'Cindy'].children..*[@.gender is female].name` => `Cindy, Helen, Eva`

And now you can see the pattern is already unbearable long due to repetition of `finding Cindy` pattern. In more complex cases, repetition will make the pattern practically unmaintainable. Currently in my application, I am using a following pattern (with a self-written preprocessor):

```
$cindy := $..*[@.name is 'Cindy']
$cindy.name + $cindy.children..*[@.gender is female].name
```

This expands to `$..*[@.name is 'Cindy'].name + $..*[@.name is 'Cindy'].children..*[@.gender is female].name`.

Another thing I am looking for is the ability to delete certain objects from collection. Suppose I need to find  __Cindy and all female offsprings of Cindy _except David's children___. I don't know if it is even possible at the current stage. Since we have '+' for union, I propose use '-' for subtraction.

(The assign operators are aligned only for aesthetics reasons)
```
$cindy           := $..*[@.name is 'Cindy']
$cindy_bloodline := $cindy.name + $cindy.children..*[@.gender is female].name
$david_bloodline := $..*[@.name is 'David'].children..*.name
$cindy_bloodline - $david_bloodline
```
