### ISSUE TITLE
Intersection and difference

### ISSUE THREAD

**Issue by felixhao28** [adriank/ObjectPath#55]
Currently we have `+` for __union__ operation to combine two or more collections together. This is very helpful in the way you can split your desired results into sub-sections and write different query paths for each. In addition to `+`, in certain use cases, more collection operators will prove their usefulness (borrowing from set theory).

I am proposing 2 new collection operators: __intersection__ and __difference__. These operations require operands to have non duplicate elements. So for these operations, there will be two modes: _by-ref_ and _by-value_. `A` and `B` are _by-ref_ equal if they have the excact same path. `A` and `B` are _by-value_ equal if they have the same primitive value or all fields of them are _by-value_ equal.

An array can be a set as long as there are no two elements equal to each other. If otherwise, duplicates are removed before performing any of the set operations.

## Intersection `^` (by-ref) and `.^` (by-value)

`A ^ B` is an intersection of `A` and `A` iff every element in `A ^ B` is contained by both `A` and `B`.

```yaml
poems:
    - name: The Bronze Horseman
      author: Pushkin
    - name: Devils
      author: Pushkin
    - name: Oh, Laziness, Come...
      author: Pushkin
    - name: Gitanjali
      author: Tagore
    - name: Manasi
      author: Tagore
    - name: Sonar Tori
      author: Tagore
novels:
    - name: Gitanjali
      author: Tagore
    - name: Noukadubi
      author: Tagore
    - name: Les Misérables
      author: Victor Hugo
```

* By-value intersection `$.poems.author .^ $.novels.author`
    - `$.poems.author` => `Pushkin, Pushkin, Pushkin, Tagore, Tagore, Tagore`
    - `$.novels.author` => `Tagore, Tagore, Victor Hugo`
    - Remove dups in `$.poems.author` => `Pushkin, Tagore`
    - `$.poems.author .^ $.novels.author` => `Tagore`
* By-ref intersection `$.poems.author ^ $.novels.author`
    - `$.poems.author` => `<poems[0].author>, ..., <poems[5].author>`
    - `$.novels.author` => `<novels[0].author>, ..., <novels[2].author>`
    - `$.poems.author ^ $.novels.author` => `<None>`
* By-ref intersection `$..*[@.author is 'Tagore'] ^ $.novels`
    - `($..*[@.author is 'Tagore']` => `<poems[3]>, <poem[4]>, <poem[5]>, <novels[0]>, <novels[1]>`
    - `$.novels` => `<novels[0]>, ..., <novels[5]>`
    - `$..*[@.author is 'Tagore'] ^ $.novels` => `<novels[0]>, <novels[1]>`
* By-value intersection `$.poems .^ $.novels` => `{name: Gitanjali, author: Tagore}`

## Difference/complement `-` and `.-`

`A - B` is a complement of `B` in `A` (or difference of `A` and `B`) iff every element in `A - B` is contained by `A` but not by `B`.

* `$.poems.author - $.novels.author` => `Pushkin, Pushkin, Pushkin, Tagore, Tagore, Tagore`
* `$.poems.author .- $.novels.author` => `Pushkin`
* `($..*[@.author is 'Tagore'] - $.novels).name` => `Gitanjali, Manasi, Sonar Tori`

For performance concerns, `A - B` should only evaluate `B` within results of `A`.
